### ISSUE TITLE
When the no of containers goes high the kubelens UI is not responsive

### ISSUE THREAD

**Issue by umatuma** [kubelens/kubelens#55]
__Description of Issue:__ UI not responsive

__API Related__

Output of `go version`:

Output of `go env`:

__Web/UI Related__

Output of `npm version`:

Output of `node -v`:

__Deployment Related__

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

Output of `helm version`:

Output of `kubectl version`:

**Comment by traviisd** [comment]
There isn't pagination (not sure how to handle that on the backend yet), and the UI could crash when rendering 100s or 1000s of pods. Might be as simple as adding https://www.npmjs.com/package/react-list to the UI.
