### ISSUE TITLE
Expand pod logs past tail 100

### ISSUE THREAD

**Issue by johndennismpls** [kubelens/kubelens#58]
the last 100 lines is often not very useful for a daemon that posts every 5 seconds.

**Comment by johndennismpls** [comment]
refreshing the page gives me `404 page not found` making it difficult to re queue and find which pod is taking the work

**Comment by traviisd** [comment]
@johndennismpls The initial log output was intended to get the last few lines of the logs which is why the "Stream Logs" functionality was put in so you can watch the logs live. However, we can up the default if you think it would be useful.

**Comment by johndennismpls** [comment]
thanks @traviisd !
