### ISSUE TITLE
Refresh tokens w/o Reloading page

### ISSUE THREAD

**Issue by johndennismpls** [kubelens/kubelens#59]
If you want to keep your eye on some logs of a pod you have to keep clicking on and off the pod to get the latest. Eventually the security token expires and you lose your place in kubelens, the only way to get back is to start from scratch.

**Comment by traviisd** [comment]
@johndennismpls Have you tried the "Stream Logs" functionality? That opens a Websocket so you can view the logs live without having to refresh. Also the routing can be configured within the helm chart to allow better navigation to a specific link within Kubelens (I can take a look at that within our org).

**Comment by johndennismpls** [comment]
"Stream Logs" works! Closing 😃
